spring.application.name=labs

spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/labs_db